workspace:
  base: /librdkafka
  path: src/github.com/Charles-WYC/librdkafka

pipeline:
  # build:
  #   image: gcc
  #   commands:
  #     - ./configure
  #     - make
  #     - make install

  mpublish:
    image: plugins/docker
    repo: xiaoyaolang/librdkafka-printpoint
    tags: ["latest"]
    secrets: [ wyc_docker_username, wyc_docker_password ]
    dockerfile: Dockerfile
    when:
      branch: master